drop table timeseries_data;
drop table timeseries;
drop table profile_map;
drop table profile;
drop table property;
drop table property_type;
drop table instrument;
drop table source;
drop table origin;
drop table reference;
drop trigger tg_star_canon on star;
drop function create_canon_name();
drop table star;
